# Config file for an example MK64: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "fov_config"

# Version of this mod.
version = "1.0.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "FOV Config"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
This mod lets you configure your field of view in Mario Kart 64 Recomp."""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Configure your field of view."

# Authors of this mod.
authors = [ "SirDiabo" ]

# ID of the target recomp game.
game_id = "mk64"

# Minimum version of the target recomp (e.g. MK64: Recompiled) that this mod can run on.
minimum_recomp_version = "0.0.9"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
# Example dependency:
#    "modname:1.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "fov_config"

# Reference symbol files.
func_reference_syms_file = "MarioKart64RecompSyms/mk64.us.syms.toml"
data_reference_syms_files = [ "MarioKart64RecompSyms/mk64.us.datasyms.toml" ]

# Additional files to include in the mod.
additional_files = [ 
    "thumb.png",
]

# Settings
[[manifest.config_options]]
id = "default_fov"
name = "Default FOV"
description = "The default, resting Field of View. Default is 0."
type = "Number"
min = 0
max = 125
step = 1.0
precision = 1
percent = false
default = 0

[[manifest.config_options]]
id = "banana_fov"
name = "Banana FOV"
description = "The Field of View, when holding a Banana or Fake Item Box. Default is 20."
type = "Number"
min = 0
max = 175
step = 1.0
precision = 1
percent = false
default = 20

[[manifest.config_options]]
id = "boost_fov"
name = "Boost FOV"
description = "The Field of View, when boosting. For example, via a Mushroom. Default is 8."
type = "Number"
min = 0
max = 175
step = 1.0
precision = 1
percent = false
default = 8

[[manifest.config_options]]
id = "ramp_fov"
name = "Boost Ramp FOV"
description = "Field of View, for when on a Boost Ramp. Those are these yellow, animated arrow things on the ground, like in Royal Raceway or Wario Stadium. Default is 20."
type = "Number"
min = 0
max = 175
step = 1.0
precision = 1
percent = false
default = 20

[[manifest.config_options]]
id = "flat_fov"
name = "Flattened FOV"
description = "Field of View, for when flattened by either a thwomp or another player after being shrunk by a lightning. Default is 25."
type = "Number"
min = 0
max = 175
step = 1.0
precision = 1
percent = false
default = 25

[[manifest.config_options]]
id = "spinout_fov"
name = "Spinout FOV"
description = "Field of View, for when spinning out, either by drifting or bumping into another heavy character. Default is 18."
type = "Number"
min = 0
max = 175
step = 1.0
precision = 1
percent = false
default = 18

[[manifest.config_options]]
id = "start_fov"
name = "Race Start FOV"
description = "Field of View, for when little starting Cutscene plays. Default is 40."
type = "Number"
min = 0
max = 100
step = 1.0
precision = 1
percent = false
default = 40